name: Flask CI

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checkout code

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run python -m unittest discover -s tests -p 'test_*.py'

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"