name: Python CI

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: 3.12
          uv-version: 0.7
      - name: Cache uv dependencies
        id: cache-uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv # Path to the uv cache directory
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Build the project
        run: uv build --sdist --wheel # Build source and wheel distributions

      - name: Run tests
        run: uv run python unittest discover -s tests -p "*.py"

      - name: Prune uv cache
        run: uv cache prune --ci

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v1
        with:
          python-version: 3.12
          uv-version: 0.7.0

      - name: Cache uv dependencies
        id: cache-uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv # Path to the uv cache directory
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Run tests
        run: python -m unittest discover -s tests -p 'test_*.py'
