name: Flask CI (uv)

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          uv-version: '0.7.0'
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          uv-version: '0.7.0'
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

      - name: Run unit tests
        run: uv run python -m unittest discover -s tests